
#define KEYBORD_ROWS_COUNT 3
#define KEYBORD_COLS_COUNT 6

#define BUTTONS_DEBUNCE_TIME 30
#define MAIN_LOOP_CYCLIC_TIME_MS  1
#define KEY_HOLD_UPDATE_PERIOD_MS 40
#define BUTTON_HOLD_DEBUNCE_TIME 500

#define LAYER_SHIFT_TOGGLE_ENABLED LAYER_SHIFT_TOGGLE
